package it.csi.gestionepazienti.gestionepazientiweb.mapper.extend;

import org.apache.ibatis.annotations.Update;

import it.csi.gestionepazienti.gestionepazientiweb.dto.RSoggettoIstituto;
import it.csi.gestionepazienti.gestionepazientiweb.mapper.generated.BaseRSoggettoIstitutoMapper;

public interface SoggettoIstitutiScolasticiMapper extends BaseRSoggettoIstitutoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table r_soggetto_istituto
	 * @mbg.generated
	 */
	@Update({ 
		"UPDATE r_soggetto_istituto ",
		" SET validita_fine=#{validitaFine,jdbcType=TIMESTAMP}, utente_operazione=#{utenteOperazione,jdbcType=VARCHAR}, ",
		" data_modifca=#{dataModifca,jdbcType=TIMESTAMP}, data_cancellazione= #{dataCancellazione,jdbcType=TIMESTAMP} ",
		" WHERE id_soggetto= #{idSoggetto,jdbcType=INTEGER} "
	})
	int updateBySoggettoId(RSoggettoIstituto record);
	

    
}
