package it.csi.gestionepazienti.gestionepazientiweb.dto.controllodati;

import it.csi.gestionepazienti.gestionepazientiweb.dto.AbstractDto;
import java.util.Date;

public class ControlloDati extends AbstractDto {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column controllo_dati.controllo_id
     *
     * @mbg.generated
     */
    private Long controlloId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column controllo_dati.controllo_code
     *
     * @mbg.generated
     */
    private String controlloCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column controllo_dati.controllo_descrizione
     *
     * @mbg.generated
     */
    private String controlloDescrizione;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column controllo_dati.controllo_istruzioni
     *
     * @mbg.generated
     */
    private String controlloIstruzioni;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column controllo_dati.controllo_severita
     *
     * @mbg.generated
     */
    private String controlloSeverita;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column controllo_dati.controllo_fun_count
     *
     * @mbg.generated
     */
    private String controlloFunCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column controllo_dati.controllo_fun_elenco
     *
     * @mbg.generated
     */
    private String controlloFunElenco;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column controllo_dati.utente_operazione
     *
     * @mbg.generated
     */
    private String utenteOperazione;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column controllo_dati.data_creazione
     *
     * @mbg.generated
     */
    private Date dataCreazione;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column controllo_dati.data_modifica
     *
     * @mbg.generated
     */
    private Date dataModifica;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column controllo_dati.data_cancellazione
     *
     * @mbg.generated
     */
    private Date dataCancellazione;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column controllo_dati.controllo_id
     *
     * @return the value of controllo_dati.controllo_id
     *
     * @mbg.generated
     */
    public Long getControlloId() {
        return controlloId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column controllo_dati.controllo_id
     *
     * @param controlloId the value for controllo_dati.controllo_id
     *
     * @mbg.generated
     */
    public void setControlloId(Long controlloId) {
        this.controlloId = controlloId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column controllo_dati.controllo_code
     *
     * @return the value of controllo_dati.controllo_code
     *
     * @mbg.generated
     */
    public String getControlloCode() {
        return controlloCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column controllo_dati.controllo_code
     *
     * @param controlloCode the value for controllo_dati.controllo_code
     *
     * @mbg.generated
     */
    public void setControlloCode(String controlloCode) {
        this.controlloCode = controlloCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column controllo_dati.controllo_descrizione
     *
     * @return the value of controllo_dati.controllo_descrizione
     *
     * @mbg.generated
     */
    public String getControlloDescrizione() {
        return controlloDescrizione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column controllo_dati.controllo_descrizione
     *
     * @param controlloDescrizione the value for controllo_dati.controllo_descrizione
     *
     * @mbg.generated
     */
    public void setControlloDescrizione(String controlloDescrizione) {
        this.controlloDescrizione = controlloDescrizione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column controllo_dati.controllo_istruzioni
     *
     * @return the value of controllo_dati.controllo_istruzioni
     *
     * @mbg.generated
     */
    public String getControlloIstruzioni() {
        return controlloIstruzioni;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column controllo_dati.controllo_istruzioni
     *
     * @param controlloIstruzioni the value for controllo_dati.controllo_istruzioni
     *
     * @mbg.generated
     */
    public void setControlloIstruzioni(String controlloIstruzioni) {
        this.controlloIstruzioni = controlloIstruzioni;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column controllo_dati.controllo_severita
     *
     * @return the value of controllo_dati.controllo_severita
     *
     * @mbg.generated
     */
    public String getControlloSeverita() {
        return controlloSeverita;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column controllo_dati.controllo_severita
     *
     * @param controlloSeverita the value for controllo_dati.controllo_severita
     *
     * @mbg.generated
     */
    public void setControlloSeverita(String controlloSeverita) {
        this.controlloSeverita = controlloSeverita;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column controllo_dati.controllo_fun_count
     *
     * @return the value of controllo_dati.controllo_fun_count
     *
     * @mbg.generated
     */
    public String getControlloFunCount() {
        return controlloFunCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column controllo_dati.controllo_fun_count
     *
     * @param controlloFunCount the value for controllo_dati.controllo_fun_count
     *
     * @mbg.generated
     */
    public void setControlloFunCount(String controlloFunCount) {
        this.controlloFunCount = controlloFunCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column controllo_dati.controllo_fun_elenco
     *
     * @return the value of controllo_dati.controllo_fun_elenco
     *
     * @mbg.generated
     */
    public String getControlloFunElenco() {
        return controlloFunElenco;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column controllo_dati.controllo_fun_elenco
     *
     * @param controlloFunElenco the value for controllo_dati.controllo_fun_elenco
     *
     * @mbg.generated
     */
    public void setControlloFunElenco(String controlloFunElenco) {
        this.controlloFunElenco = controlloFunElenco;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column controllo_dati.utente_operazione
     *
     * @return the value of controllo_dati.utente_operazione
     *
     * @mbg.generated
     */
    public String getUtenteOperazione() {
        return utenteOperazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column controllo_dati.utente_operazione
     *
     * @param utenteOperazione the value for controllo_dati.utente_operazione
     *
     * @mbg.generated
     */
    public void setUtenteOperazione(String utenteOperazione) {
        this.utenteOperazione = utenteOperazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column controllo_dati.data_creazione
     *
     * @return the value of controllo_dati.data_creazione
     *
     * @mbg.generated
     */
    public Date getDataCreazione() {
        return dataCreazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column controllo_dati.data_creazione
     *
     * @param dataCreazione the value for controllo_dati.data_creazione
     *
     * @mbg.generated
     */
    public void setDataCreazione(Date dataCreazione) {
        this.dataCreazione = dataCreazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column controllo_dati.data_modifica
     *
     * @return the value of controllo_dati.data_modifica
     *
     * @mbg.generated
     */
    public Date getDataModifica() {
        return dataModifica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column controllo_dati.data_modifica
     *
     * @param dataModifica the value for controllo_dati.data_modifica
     *
     * @mbg.generated
     */
    public void setDataModifica(Date dataModifica) {
        this.dataModifica = dataModifica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column controllo_dati.data_cancellazione
     *
     * @return the value of controllo_dati.data_cancellazione
     *
     * @mbg.generated
     */
    public Date getDataCancellazione() {
        return dataCancellazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column controllo_dati.data_cancellazione
     *
     * @param dataCancellazione the value for controllo_dati.data_cancellazione
     *
     * @mbg.generated
     */
    public void setDataCancellazione(Date dataCancellazione) {
        this.dataCancellazione = dataCancellazione;
    }
}