let LOCAL_DEV = ''
if (location.hostname === 'localhost' || location.hostname === '127.0.0.1') {
  LOCAL_DEV = 'http://localhost:8080/visurammgweb/'
  // LOCAL_DEV = 'https://int-rupcovid.sdp.csi.it/visurammgweb/'
}

const VERSION = '1.6'

const VISURAMMG_BASE_URL = LOCAL_DEV + 'api'
const VISURAMMG_EXTERNAL_URL = LOCAL_DEV + 'external/api/uscammg/'

const ID_ISOLAMENTO_DOMICILIARE = 1
const ID_RICOVERATO = 2
const ID_TRASFERITO_INTERNO = 3
const ID_TRASFERITO_ESTERNO = 4
const ID_DECEDUTO = 5
const ID_GUARITO = 6
const ID_ATTESA_TEST = 8
const ID_POST_RICOVERO = 9
const ID_ASSEGNAZIONE_DOMICILIO = 10
const ID_SEGNALAZIONE = 11
const ID_PRESA_IN_CARICO = 12
const ID_USCITO = 13
const ID_INFO_DA_INTEGRARE = 14

const ESITO_TAMPONE = {
  1: 'In corso',
  2: 'Positivo',
  4: 'Negativo',
  6: 'Sospeso',
  7: 'Non idoneo',
  8: 'Non pervenuto'
}

const SINTOMO_NUOVO_CODICI = {
  ANORESSIA: '012',
  BRIVIDO: '017',
  CEFALEA: '007',
  CONGIUNTIVITE: '019',
  DIARREA: '002',
  DISPNEA: '001',
  DOLORI_MUSCOLARI: '010',
  FARINGODINIA: '021',
  GUSTO: 'GUSTO',
  NAUSEA_E_VOMITO: '005',
  OLFATTO: '011',
  RAFFREDDORE: '018',
  STANCHEZZA: '016',
  TEMPREATURA: '013',
  TOSSE: '020',
  VERTIGINI: '015'
}

const SCHEDA_STATI = {
  BOZZA: 'B',
  INVIATA: 'I',
  RIFIUTATA: 'R',
  ACCETTATA: 'P',
  EVASA: 'E'
}

const SCHEDA_STATI_LABEL = {
  BOZZA: 'Bozza',
  INVIATA: 'In Attesa',
  RIFIUTATA: 'Rifiutata',
  ACCETTATA: 'In carico',
  EVASA: 'Evasa',
  [SCHEDA_STATI.BOZZA]: 'Bozza',
  [SCHEDA_STATI.INVIATA]: 'In Attesa',
  [SCHEDA_STATI.RIFIUTATA]: 'Rifiutata',
  [SCHEDA_STATI.ACCETTATA]: 'In carico',
  [SCHEDA_STATI.EVASA]: 'Evasa'
}

export default {
  VISURAMMG_BASE_URL: VISURAMMG_BASE_URL,
  VISURAMMG_EXTERNAL_URL: VISURAMMG_EXTERNAL_URL,
  ID_ISOLAMENTO_DOMICILIARE: ID_ISOLAMENTO_DOMICILIARE,
  ID_RICOVERATO: ID_RICOVERATO,
  ID_TRASFERITO_INTERNO: ID_TRASFERITO_INTERNO,
  ID_TRASFERITO_ESTERNO: ID_TRASFERITO_ESTERNO,
  ID_DECEDUTO: ID_DECEDUTO,
  ID_GUARITO: ID_GUARITO,
  ID_ATTESA_TEST: ID_ATTESA_TEST,
  ID_POST_RICOVERO: ID_POST_RICOVERO,
  ID_ASSEGNAZIONE_DOMICILIO: ID_ASSEGNAZIONE_DOMICILIO,
  ID_SEGNALAZIONE: ID_SEGNALAZIONE,
  ID_PRESA_IN_CARICO: ID_PRESA_IN_CARICO,
  ID_USCITO: ID_USCITO,
  ID_INFO_DA_INTEGRARE: ID_INFO_DA_INTEGRARE,
  ESITO_TAMPONE: ESITO_TAMPONE,
  VERSION: VERSION,
  SINTOMO_NUOVO_CODICI,
  SCHEDA_STATI,
  SCHEDA_STATI_LABEL
}
