package it.csi.gestionepazienti.gestionepazientiweb.dto.test;

import it.csi.gestionepazienti.gestionepazientiweb.dto.AbstractDto;
import java.util.Date;

public class Test extends AbstractDto {
    /**
	 * 
	 */
	private static final long serialVersionUID = -5025036097847909956L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.test_id
     *
     * @mbg.generated
     */
    private Long testId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.test_data_esecuzione
     *
     * @mbg.generated
     */
    private Date testDataEsecuzione;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.test_range_riferimento
     *
     * @mbg.generated
     */
    private String testRangeRiferimento;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.test_valore
     *
     * @mbg.generated
     */
    private String testValore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.test_unita_misura
     *
     * @mbg.generated
     */
    private String testUnitaMisura;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.test_codice_esito
     *
     * @mbg.generated
     */
    private String testCodiceEsito;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.test_laboratorio_desc
     *
     * @mbg.generated
     */
    private String testLaboratorioDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.test_programma
     *
     * @mbg.generated
     */
    private String testProgramma;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.id_soggetto
     *
     * @mbg.generated
     */
    private Long idSoggetto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.test_esito_id
     *
     * @mbg.generated
     */
    private Integer testEsitoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.test_tipo_id
     *
     * @mbg.generated
     */
    private Integer testTipoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.test_richiesta_tipo_id
     *
     * @mbg.generated
     */
    private Integer testRichiestaTipoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.intfrdet_id
     *
     * @mbg.generated
     */
    private Integer intfrdetId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.utente_operazione
     *
     * @mbg.generated
     */
    private String utenteOperazione;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.data_creazione
     *
     * @mbg.generated
     */
    private Date dataCreazione;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.data_modifica
     *
     * @mbg.generated
     */
    private Date dataModifica;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column test.data_cancellazione
     *
     * @mbg.generated
     */
    private Date dataCancellazione;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.test_id
     *
     * @return the value of test.test_id
     *
     * @mbg.generated
     */
    public Long getTestId() {
        return testId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.test_id
     *
     * @param testId the value for test.test_id
     *
     * @mbg.generated
     */
    public void setTestId(Long testId) {
        this.testId = testId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.test_data_esecuzione
     *
     * @return the value of test.test_data_esecuzione
     *
     * @mbg.generated
     */
    public Date getTestDataEsecuzione() {
        return testDataEsecuzione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.test_data_esecuzione
     *
     * @param testDataEsecuzione the value for test.test_data_esecuzione
     *
     * @mbg.generated
     */
    public void setTestDataEsecuzione(Date testDataEsecuzione) {
        this.testDataEsecuzione = testDataEsecuzione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.test_range_riferimento
     *
     * @return the value of test.test_range_riferimento
     *
     * @mbg.generated
     */
    public String getTestRangeRiferimento() {
        return testRangeRiferimento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.test_range_riferimento
     *
     * @param testRangeRiferimento the value for test.test_range_riferimento
     *
     * @mbg.generated
     */
    public void setTestRangeRiferimento(String testRangeRiferimento) {
        this.testRangeRiferimento = testRangeRiferimento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.test_valore
     *
     * @return the value of test.test_valore
     *
     * @mbg.generated
     */
    public String getTestValore() {
        return testValore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.test_valore
     *
     * @param testValore the value for test.test_valore
     *
     * @mbg.generated
     */
    public void setTestValore(String testValore) {
        this.testValore = testValore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.test_unita_misura
     *
     * @return the value of test.test_unita_misura
     *
     * @mbg.generated
     */
    public String getTestUnitaMisura() {
        return testUnitaMisura;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.test_unita_misura
     *
     * @param testUnitaMisura the value for test.test_unita_misura
     *
     * @mbg.generated
     */
    public void setTestUnitaMisura(String testUnitaMisura) {
        this.testUnitaMisura = testUnitaMisura;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.test_codice_esito
     *
     * @return the value of test.test_codice_esito
     *
     * @mbg.generated
     */
    public String getTestCodiceEsito() {
        return testCodiceEsito;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.test_codice_esito
     *
     * @param testCodiceEsito the value for test.test_codice_esito
     *
     * @mbg.generated
     */
    public void setTestCodiceEsito(String testCodiceEsito) {
        this.testCodiceEsito = testCodiceEsito;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.test_laboratorio_desc
     *
     * @return the value of test.test_laboratorio_desc
     *
     * @mbg.generated
     */
    public String getTestLaboratorioDesc() {
        return testLaboratorioDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.test_laboratorio_desc
     *
     * @param testLaboratorioDesc the value for test.test_laboratorio_desc
     *
     * @mbg.generated
     */
    public void setTestLaboratorioDesc(String testLaboratorioDesc) {
        this.testLaboratorioDesc = testLaboratorioDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.test_programma
     *
     * @return the value of test.test_programma
     *
     * @mbg.generated
     */
    public String getTestProgramma() {
        return testProgramma;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.test_programma
     *
     * @param testProgramma the value for test.test_programma
     *
     * @mbg.generated
     */
    public void setTestProgramma(String testProgramma) {
        this.testProgramma = testProgramma;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.id_soggetto
     *
     * @return the value of test.id_soggetto
     *
     * @mbg.generated
     */
    public Long getIdSoggetto() {
        return idSoggetto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.id_soggetto
     *
     * @param idSoggetto the value for test.id_soggetto
     *
     * @mbg.generated
     */
    public void setIdSoggetto(Long idSoggetto) {
        this.idSoggetto = idSoggetto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.test_esito_id
     *
     * @return the value of test.test_esito_id
     *
     * @mbg.generated
     */
    public Integer getTestEsitoId() {
        return testEsitoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.test_esito_id
     *
     * @param testEsitoId the value for test.test_esito_id
     *
     * @mbg.generated
     */
    public void setTestEsitoId(Integer testEsitoId) {
        this.testEsitoId = testEsitoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.test_tipo_id
     *
     * @return the value of test.test_tipo_id
     *
     * @mbg.generated
     */
    public Integer getTestTipoId() {
        return testTipoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.test_tipo_id
     *
     * @param testTipoId the value for test.test_tipo_id
     *
     * @mbg.generated
     */
    public void setTestTipoId(Integer testTipoId) {
        this.testTipoId = testTipoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.test_richiesta_tipo_id
     *
     * @return the value of test.test_richiesta_tipo_id
     *
     * @mbg.generated
     */
    public Integer getTestRichiestaTipoId() {
        return testRichiestaTipoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.test_richiesta_tipo_id
     *
     * @param testRichiestaTipoId the value for test.test_richiesta_tipo_id
     *
     * @mbg.generated
     */
    public void setTestRichiestaTipoId(Integer testRichiestaTipoId) {
        this.testRichiestaTipoId = testRichiestaTipoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.intfrdet_id
     *
     * @return the value of test.intfrdet_id
     *
     * @mbg.generated
     */
    public Integer getIntfrdetId() {
        return intfrdetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.intfrdet_id
     *
     * @param intfrdetId the value for test.intfrdet_id
     *
     * @mbg.generated
     */
    public void setIntfrdetId(Integer intfrdetId) {
        this.intfrdetId = intfrdetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.utente_operazione
     *
     * @return the value of test.utente_operazione
     *
     * @mbg.generated
     */
    public String getUtenteOperazione() {
        return utenteOperazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.utente_operazione
     *
     * @param utenteOperazione the value for test.utente_operazione
     *
     * @mbg.generated
     */
    public void setUtenteOperazione(String utenteOperazione) {
        this.utenteOperazione = utenteOperazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.data_creazione
     *
     * @return the value of test.data_creazione
     *
     * @mbg.generated
     */
    public Date getDataCreazione() {
        return dataCreazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.data_creazione
     *
     * @param dataCreazione the value for test.data_creazione
     *
     * @mbg.generated
     */
    public void setDataCreazione(Date dataCreazione) {
        this.dataCreazione = dataCreazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.data_modifica
     *
     * @return the value of test.data_modifica
     *
     * @mbg.generated
     */
    public Date getDataModifica() {
        return dataModifica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.data_modifica
     *
     * @param dataModifica the value for test.data_modifica
     *
     * @mbg.generated
     */
    public void setDataModifica(Date dataModifica) {
        this.dataModifica = dataModifica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column test.data_cancellazione
     *
     * @return the value of test.data_cancellazione
     *
     * @mbg.generated
     */
    public Date getDataCancellazione() {
        return dataCancellazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column test.data_cancellazione
     *
     * @param dataCancellazione the value for test.data_cancellazione
     *
     * @mbg.generated
     */
    public void setDataCancellazione(Date dataCancellazione) {
        this.dataCancellazione = dataCancellazione;
    }
}