package it.csi.gestionepazienti.gestionepazientiweb.dto.test;

import it.csi.gestionepazienti.gestionepazientiweb.dto.AbstractDto;
import java.util.Date;

public class TestEsito extends AbstractDto {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_test_esito.test_esito_id
     *
     * @mbg.generated
     */
    private Integer testEsitoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_test_esito.test_esito_cod
     *
     * @mbg.generated
     */
    private String testEsitoCod;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_test_esito.test_esito_desc
     *
     * @mbg.generated
     */
    private String testEsitoDesc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_test_esito.validita_inizio
     *
     * @mbg.generated
     */
    private Date validitaInizio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_test_esito.validita_fine
     *
     * @mbg.generated
     */
    private Date validitaFine;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_test_esito.utente_operazione
     *
     * @mbg.generated
     */
    private String utenteOperazione;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_test_esito.data_creazione
     *
     * @mbg.generated
     */
    private Date dataCreazione;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_test_esito.data_modifica
     *
     * @mbg.generated
     */
    private Date dataModifica;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column d_test_esito.data_cancellazione
     *
     * @mbg.generated
     */
    private Date dataCancellazione;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_test_esito.test_esito_id
     *
     * @return the value of d_test_esito.test_esito_id
     *
     * @mbg.generated
     */
    public Integer getTestEsitoId() {
        return testEsitoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_test_esito.test_esito_id
     *
     * @param testEsitoId the value for d_test_esito.test_esito_id
     *
     * @mbg.generated
     */
    public void setTestEsitoId(Integer testEsitoId) {
        this.testEsitoId = testEsitoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_test_esito.test_esito_cod
     *
     * @return the value of d_test_esito.test_esito_cod
     *
     * @mbg.generated
     */
    public String getTestEsitoCod() {
        return testEsitoCod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_test_esito.test_esito_cod
     *
     * @param testEsitoCod the value for d_test_esito.test_esito_cod
     *
     * @mbg.generated
     */
    public void setTestEsitoCod(String testEsitoCod) {
        this.testEsitoCod = testEsitoCod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_test_esito.test_esito_desc
     *
     * @return the value of d_test_esito.test_esito_desc
     *
     * @mbg.generated
     */
    public String getTestEsitoDesc() {
        return testEsitoDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_test_esito.test_esito_desc
     *
     * @param testEsitoDesc the value for d_test_esito.test_esito_desc
     *
     * @mbg.generated
     */
    public void setTestEsitoDesc(String testEsitoDesc) {
        this.testEsitoDesc = testEsitoDesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_test_esito.validita_inizio
     *
     * @return the value of d_test_esito.validita_inizio
     *
     * @mbg.generated
     */
    public Date getValiditaInizio() {
        return validitaInizio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_test_esito.validita_inizio
     *
     * @param validitaInizio the value for d_test_esito.validita_inizio
     *
     * @mbg.generated
     */
    public void setValiditaInizio(Date validitaInizio) {
        this.validitaInizio = validitaInizio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_test_esito.validita_fine
     *
     * @return the value of d_test_esito.validita_fine
     *
     * @mbg.generated
     */
    public Date getValiditaFine() {
        return validitaFine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_test_esito.validita_fine
     *
     * @param validitaFine the value for d_test_esito.validita_fine
     *
     * @mbg.generated
     */
    public void setValiditaFine(Date validitaFine) {
        this.validitaFine = validitaFine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_test_esito.utente_operazione
     *
     * @return the value of d_test_esito.utente_operazione
     *
     * @mbg.generated
     */
    public String getUtenteOperazione() {
        return utenteOperazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_test_esito.utente_operazione
     *
     * @param utenteOperazione the value for d_test_esito.utente_operazione
     *
     * @mbg.generated
     */
    public void setUtenteOperazione(String utenteOperazione) {
        this.utenteOperazione = utenteOperazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_test_esito.data_creazione
     *
     * @return the value of d_test_esito.data_creazione
     *
     * @mbg.generated
     */
    public Date getDataCreazione() {
        return dataCreazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_test_esito.data_creazione
     *
     * @param dataCreazione the value for d_test_esito.data_creazione
     *
     * @mbg.generated
     */
    public void setDataCreazione(Date dataCreazione) {
        this.dataCreazione = dataCreazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_test_esito.data_modifica
     *
     * @return the value of d_test_esito.data_modifica
     *
     * @mbg.generated
     */
    public Date getDataModifica() {
        return dataModifica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_test_esito.data_modifica
     *
     * @param dataModifica the value for d_test_esito.data_modifica
     *
     * @mbg.generated
     */
    public void setDataModifica(Date dataModifica) {
        this.dataModifica = dataModifica;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column d_test_esito.data_cancellazione
     *
     * @return the value of d_test_esito.data_cancellazione
     *
     * @mbg.generated
     */
    public Date getDataCancellazione() {
        return dataCancellazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column d_test_esito.data_cancellazione
     *
     * @param dataCancellazione the value for d_test_esito.data_cancellazione
     *
     * @mbg.generated
     */
    public void setDataCancellazione(Date dataCancellazione) {
        this.dataCancellazione = dataCancellazione;
    }
}