package it.csi.gestionepazienti.gestionepazientiweb.dto.referto;

import it.csi.gestionepazienti.gestionepazientiweb.dto.AbstractDto;
import java.util.Date;

public class Elaborazione extends AbstractDto {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dmarefcovid_l_elaborazione.elab_id
     *
     * @mbg.generated
     */
    private Long elabId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dmarefcovid_l_elaborazione.elab_function_name
     *
     * @mbg.generated
     */
    private String elabFunctionName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dmarefcovid_l_elaborazione.elab_inizio
     *
     * @mbg.generated
     */
    private Date elabInizio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dmarefcovid_l_elaborazione.elab_fine
     *
     * @mbg.generated
     */
    private Date elabFine;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dmarefcovid_l_elaborazione.elab_exit_code
     *
     * @mbg.generated
     */
    private String elabExitCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dmarefcovid_l_elaborazione.elab_exit_message
     *
     * @mbg.generated
     */
    private String elabExitMessage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dmarefcovid_l_elaborazione.data_creazione
     *
     * @mbg.generated
     */
    private Date dataCreazione;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dmarefcovid_l_elaborazione.utente_operazione
     *
     * @mbg.generated
     */
    private String utenteOperazione;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dmarefcovid_l_elaborazione.elab_id
     *
     * @return the value of dmarefcovid_l_elaborazione.elab_id
     *
     * @mbg.generated
     */
    public Long getElabId() {
        return elabId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dmarefcovid_l_elaborazione.elab_id
     *
     * @param elabId the value for dmarefcovid_l_elaborazione.elab_id
     *
     * @mbg.generated
     */
    public void setElabId(Long elabId) {
        this.elabId = elabId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dmarefcovid_l_elaborazione.elab_function_name
     *
     * @return the value of dmarefcovid_l_elaborazione.elab_function_name
     *
     * @mbg.generated
     */
    public String getElabFunctionName() {
        return elabFunctionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dmarefcovid_l_elaborazione.elab_function_name
     *
     * @param elabFunctionName the value for dmarefcovid_l_elaborazione.elab_function_name
     *
     * @mbg.generated
     */
    public void setElabFunctionName(String elabFunctionName) {
        this.elabFunctionName = elabFunctionName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dmarefcovid_l_elaborazione.elab_inizio
     *
     * @return the value of dmarefcovid_l_elaborazione.elab_inizio
     *
     * @mbg.generated
     */
    public Date getElabInizio() {
        return elabInizio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dmarefcovid_l_elaborazione.elab_inizio
     *
     * @param elabInizio the value for dmarefcovid_l_elaborazione.elab_inizio
     *
     * @mbg.generated
     */
    public void setElabInizio(Date elabInizio) {
        this.elabInizio = elabInizio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dmarefcovid_l_elaborazione.elab_fine
     *
     * @return the value of dmarefcovid_l_elaborazione.elab_fine
     *
     * @mbg.generated
     */
    public Date getElabFine() {
        return elabFine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dmarefcovid_l_elaborazione.elab_fine
     *
     * @param elabFine the value for dmarefcovid_l_elaborazione.elab_fine
     *
     * @mbg.generated
     */
    public void setElabFine(Date elabFine) {
        this.elabFine = elabFine;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dmarefcovid_l_elaborazione.elab_exit_code
     *
     * @return the value of dmarefcovid_l_elaborazione.elab_exit_code
     *
     * @mbg.generated
     */
    public String getElabExitCode() {
        return elabExitCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dmarefcovid_l_elaborazione.elab_exit_code
     *
     * @param elabExitCode the value for dmarefcovid_l_elaborazione.elab_exit_code
     *
     * @mbg.generated
     */
    public void setElabExitCode(String elabExitCode) {
        this.elabExitCode = elabExitCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dmarefcovid_l_elaborazione.elab_exit_message
     *
     * @return the value of dmarefcovid_l_elaborazione.elab_exit_message
     *
     * @mbg.generated
     */
    public String getElabExitMessage() {
        return elabExitMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dmarefcovid_l_elaborazione.elab_exit_message
     *
     * @param elabExitMessage the value for dmarefcovid_l_elaborazione.elab_exit_message
     *
     * @mbg.generated
     */
    public void setElabExitMessage(String elabExitMessage) {
        this.elabExitMessage = elabExitMessage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dmarefcovid_l_elaborazione.data_creazione
     *
     * @return the value of dmarefcovid_l_elaborazione.data_creazione
     *
     * @mbg.generated
     */
    public Date getDataCreazione() {
        return dataCreazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dmarefcovid_l_elaborazione.data_creazione
     *
     * @param dataCreazione the value for dmarefcovid_l_elaborazione.data_creazione
     *
     * @mbg.generated
     */
    public void setDataCreazione(Date dataCreazione) {
        this.dataCreazione = dataCreazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dmarefcovid_l_elaborazione.utente_operazione
     *
     * @return the value of dmarefcovid_l_elaborazione.utente_operazione
     *
     * @mbg.generated
     */
    public String getUtenteOperazione() {
        return utenteOperazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dmarefcovid_l_elaborazione.utente_operazione
     *
     * @param utenteOperazione the value for dmarefcovid_l_elaborazione.utente_operazione
     *
     * @mbg.generated
     */
    public void setUtenteOperazione(String utenteOperazione) {
        this.utenteOperazione = utenteOperazione;
    }
}