package it.csi.gestionepazienti.gestionepazientiweb.dto.referto;

import it.csi.gestionepazienti.gestionepazientiweb.dto.AbstractDto;
import java.util.Date;

public class Referto extends AbstractDto {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dmarefcovid_t_referto.id_messaggio
     *
     * @mbg.generated
     */
    private Integer idMessaggio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dmarefcovid_t_referto.codfisc
     *
     * @mbg.generated
     */
    private String codfisc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dmarefcovid_t_referto.cognome
     *
     * @mbg.generated
     */
    private String cognome;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dmarefcovid_t_referto.nome
     *
     * @mbg.generated
     */
    private String nome;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dmarefcovid_t_referto.sesso
     *
     * @mbg.generated
     */
    private String sesso;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dmarefcovid_t_referto.datanascita
     *
     * @mbg.generated
     */
    private Date datanascita;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dmarefcovid_t_referto.comunenascita
     *
     * @mbg.generated
     */
    private String comunenascita;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dmarefcovid_t_referto.legalauthenticator
     *
     * @mbg.generated
     */
    private String legalauthenticator;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dmarefcovid_t_referto.cod_cl
     *
     * @mbg.generated
     */
    private String codCl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dmarefcovid_t_referto.id_repository
     *
     * @mbg.generated
     */
    private String idRepository;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dmarefcovid_t_referto.id_documento
     *
     * @mbg.generated
     */
    private String idDocumento;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dmarefcovid_t_referto.id_aura
     *
     * @mbg.generated
     */
    private String idAura;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dmarefcovid_t_referto.res_addr
     *
     * @mbg.generated
     */
    private String resAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dmarefcovid_t_referto.res_istat
     *
     * @mbg.generated
     */
    private String resIstat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dmarefcovid_t_referto.dom_addr
     *
     * @mbg.generated
     */
    private String domAddr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dmarefcovid_t_referto.dom_istat
     *
     * @mbg.generated
     */
    private String domIstat;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dmarefcovid_t_referto.asr
     *
     * @mbg.generated
     */
    private String asr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dmarefcovid_t_referto.id_struttura
     *
     * @mbg.generated
     */
    private Long idStruttura;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dmarefcovid_t_referto.descr_struttura
     *
     * @mbg.generated
     */
    private String descrStruttura;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dmarefcovid_t_referto.matricola_struttura
     *
     * @mbg.generated
     */
    private String matricolaStruttura;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dmarefcovid_t_referto.annullamento_episodio
     *
     * @mbg.generated
     */
    private String annullamentoEpisodio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dmarefcovid_t_referto.documento_tipo_azione
     *
     * @mbg.generated
     */
    private String documentoTipoAzione;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dmarefcovid_t_referto.episodio_tipo_azione
     *
     * @mbg.generated
     */
    private String episodioTipoAzione;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dmarefcovid_t_referto.data_creazione
     *
     * @mbg.generated
     */
    private Date dataCreazione;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dmarefcovid_t_referto.ts_msg_ricevuto
     *
     * @mbg.generated
     */
    private Date tsMsgRicevuto;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dmarefcovid_t_referto.ts_cda2_elaborato
     *
     * @mbg.generated
     */
    private Date tsCda2Elaborato;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dmarefcovid_t_referto.asr_doc
     *
     * @mbg.generated
     */
    private String asrDoc;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dmarefcovid_t_referto.cod_tipo_richiesta
     *
     * @mbg.generated
     */
    private String codTipoRichiesta;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dmarefcovid_t_referto.programma
     *
     * @mbg.generated
     */
    private String programma;
    
    private String utenteoperazione;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dmarefcovid_t_referto.asl_laboratorio
     *
     * @mbg.generated
     */
    private String aslLaboratorio;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dmarefcovid_t_referto.id_messaggio
     *
     * @return the value of dmarefcovid_t_referto.id_messaggio
     *
     * @mbg.generated
     */
    public Integer getIdMessaggio() {
        return idMessaggio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dmarefcovid_t_referto.id_messaggio
     *
     * @param idMessaggio the value for dmarefcovid_t_referto.id_messaggio
     *
     * @mbg.generated
     */
    public void setIdMessaggio(Integer idMessaggio) {
        this.idMessaggio = idMessaggio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dmarefcovid_t_referto.codfisc
     *
     * @return the value of dmarefcovid_t_referto.codfisc
     *
     * @mbg.generated
     */
    public String getCodfisc() {
        return codfisc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dmarefcovid_t_referto.codfisc
     *
     * @param codfisc the value for dmarefcovid_t_referto.codfisc
     *
     * @mbg.generated
     */
    public void setCodfisc(String codfisc) {
        this.codfisc = codfisc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dmarefcovid_t_referto.cognome
     *
     * @return the value of dmarefcovid_t_referto.cognome
     *
     * @mbg.generated
     */
    public String getCognome() {
        return cognome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dmarefcovid_t_referto.cognome
     *
     * @param cognome the value for dmarefcovid_t_referto.cognome
     *
     * @mbg.generated
     */
    public void setCognome(String cognome) {
        this.cognome = cognome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dmarefcovid_t_referto.nome
     *
     * @return the value of dmarefcovid_t_referto.nome
     *
     * @mbg.generated
     */
    public String getNome() {
        return nome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dmarefcovid_t_referto.nome
     *
     * @param nome the value for dmarefcovid_t_referto.nome
     *
     * @mbg.generated
     */
    public void setNome(String nome) {
        this.nome = nome;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dmarefcovid_t_referto.sesso
     *
     * @return the value of dmarefcovid_t_referto.sesso
     *
     * @mbg.generated
     */
    public String getSesso() {
        return sesso;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dmarefcovid_t_referto.sesso
     *
     * @param sesso the value for dmarefcovid_t_referto.sesso
     *
     * @mbg.generated
     */
    public void setSesso(String sesso) {
        this.sesso = sesso;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dmarefcovid_t_referto.datanascita
     *
     * @return the value of dmarefcovid_t_referto.datanascita
     *
     * @mbg.generated
     */
    public Date getDatanascita() {
        return datanascita;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dmarefcovid_t_referto.datanascita
     *
     * @param datanascita the value for dmarefcovid_t_referto.datanascita
     *
     * @mbg.generated
     */
    public void setDatanascita(Date datanascita) {
        this.datanascita = datanascita;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dmarefcovid_t_referto.comunenascita
     *
     * @return the value of dmarefcovid_t_referto.comunenascita
     *
     * @mbg.generated
     */
    public String getComunenascita() {
        return comunenascita;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dmarefcovid_t_referto.comunenascita
     *
     * @param comunenascita the value for dmarefcovid_t_referto.comunenascita
     *
     * @mbg.generated
     */
    public void setComunenascita(String comunenascita) {
        this.comunenascita = comunenascita;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dmarefcovid_t_referto.legalauthenticator
     *
     * @return the value of dmarefcovid_t_referto.legalauthenticator
     *
     * @mbg.generated
     */
    public String getLegalauthenticator() {
        return legalauthenticator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dmarefcovid_t_referto.legalauthenticator
     *
     * @param legalauthenticator the value for dmarefcovid_t_referto.legalauthenticator
     *
     * @mbg.generated
     */
    public void setLegalauthenticator(String legalauthenticator) {
        this.legalauthenticator = legalauthenticator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dmarefcovid_t_referto.cod_cl
     *
     * @return the value of dmarefcovid_t_referto.cod_cl
     *
     * @mbg.generated
     */
    public String getCodCl() {
        return codCl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dmarefcovid_t_referto.cod_cl
     *
     * @param codCl the value for dmarefcovid_t_referto.cod_cl
     *
     * @mbg.generated
     */
    public void setCodCl(String codCl) {
        this.codCl = codCl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dmarefcovid_t_referto.id_repository
     *
     * @return the value of dmarefcovid_t_referto.id_repository
     *
     * @mbg.generated
     */
    public String getIdRepository() {
        return idRepository;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dmarefcovid_t_referto.id_repository
     *
     * @param idRepository the value for dmarefcovid_t_referto.id_repository
     *
     * @mbg.generated
     */
    public void setIdRepository(String idRepository) {
        this.idRepository = idRepository;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dmarefcovid_t_referto.id_documento
     *
     * @return the value of dmarefcovid_t_referto.id_documento
     *
     * @mbg.generated
     */
    public String getIdDocumento() {
        return idDocumento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dmarefcovid_t_referto.id_documento
     *
     * @param idDocumento the value for dmarefcovid_t_referto.id_documento
     *
     * @mbg.generated
     */
    public void setIdDocumento(String idDocumento) {
        this.idDocumento = idDocumento;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dmarefcovid_t_referto.id_aura
     *
     * @return the value of dmarefcovid_t_referto.id_aura
     *
     * @mbg.generated
     */
    public String getIdAura() {
        return idAura;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dmarefcovid_t_referto.id_aura
     *
     * @param idAura the value for dmarefcovid_t_referto.id_aura
     *
     * @mbg.generated
     */
    public void setIdAura(String idAura) {
        this.idAura = idAura;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dmarefcovid_t_referto.res_addr
     *
     * @return the value of dmarefcovid_t_referto.res_addr
     *
     * @mbg.generated
     */
    public String getResAddr() {
        return resAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dmarefcovid_t_referto.res_addr
     *
     * @param resAddr the value for dmarefcovid_t_referto.res_addr
     *
     * @mbg.generated
     */
    public void setResAddr(String resAddr) {
        this.resAddr = resAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dmarefcovid_t_referto.res_istat
     *
     * @return the value of dmarefcovid_t_referto.res_istat
     *
     * @mbg.generated
     */
    public String getResIstat() {
        return resIstat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dmarefcovid_t_referto.res_istat
     *
     * @param resIstat the value for dmarefcovid_t_referto.res_istat
     *
     * @mbg.generated
     */
    public void setResIstat(String resIstat) {
        this.resIstat = resIstat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dmarefcovid_t_referto.dom_addr
     *
     * @return the value of dmarefcovid_t_referto.dom_addr
     *
     * @mbg.generated
     */
    public String getDomAddr() {
        return domAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dmarefcovid_t_referto.dom_addr
     *
     * @param domAddr the value for dmarefcovid_t_referto.dom_addr
     *
     * @mbg.generated
     */
    public void setDomAddr(String domAddr) {
        this.domAddr = domAddr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dmarefcovid_t_referto.dom_istat
     *
     * @return the value of dmarefcovid_t_referto.dom_istat
     *
     * @mbg.generated
     */
    public String getDomIstat() {
        return domIstat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dmarefcovid_t_referto.dom_istat
     *
     * @param domIstat the value for dmarefcovid_t_referto.dom_istat
     *
     * @mbg.generated
     */
    public void setDomIstat(String domIstat) {
        this.domIstat = domIstat;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dmarefcovid_t_referto.asr
     *
     * @return the value of dmarefcovid_t_referto.asr
     *
     * @mbg.generated
     */
    public String getAsr() {
        return asr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dmarefcovid_t_referto.asr
     *
     * @param asr the value for dmarefcovid_t_referto.asr
     *
     * @mbg.generated
     */
    public void setAsr(String asr) {
        this.asr = asr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dmarefcovid_t_referto.id_struttura
     *
     * @return the value of dmarefcovid_t_referto.id_struttura
     *
     * @mbg.generated
     */
    public Long getIdStruttura() {
        return idStruttura;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dmarefcovid_t_referto.id_struttura
     *
     * @param idStruttura the value for dmarefcovid_t_referto.id_struttura
     *
     * @mbg.generated
     */
    public void setIdStruttura(Long idStruttura) {
        this.idStruttura = idStruttura;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dmarefcovid_t_referto.descr_struttura
     *
     * @return the value of dmarefcovid_t_referto.descr_struttura
     *
     * @mbg.generated
     */
    public String getDescrStruttura() {
        return descrStruttura;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dmarefcovid_t_referto.descr_struttura
     *
     * @param descrStruttura the value for dmarefcovid_t_referto.descr_struttura
     *
     * @mbg.generated
     */
    public void setDescrStruttura(String descrStruttura) {
        this.descrStruttura = descrStruttura;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dmarefcovid_t_referto.matricola_struttura
     *
     * @return the value of dmarefcovid_t_referto.matricola_struttura
     *
     * @mbg.generated
     */
    public String getMatricolaStruttura() {
        return matricolaStruttura;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dmarefcovid_t_referto.matricola_struttura
     *
     * @param matricolaStruttura the value for dmarefcovid_t_referto.matricola_struttura
     *
     * @mbg.generated
     */
    public void setMatricolaStruttura(String matricolaStruttura) {
        this.matricolaStruttura = matricolaStruttura;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dmarefcovid_t_referto.annullamento_episodio
     *
     * @return the value of dmarefcovid_t_referto.annullamento_episodio
     *
     * @mbg.generated
     */
    public String getAnnullamentoEpisodio() {
        return annullamentoEpisodio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dmarefcovid_t_referto.annullamento_episodio
     *
     * @param annullamentoEpisodio the value for dmarefcovid_t_referto.annullamento_episodio
     *
     * @mbg.generated
     */
    public void setAnnullamentoEpisodio(String annullamentoEpisodio) {
        this.annullamentoEpisodio = annullamentoEpisodio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dmarefcovid_t_referto.documento_tipo_azione
     *
     * @return the value of dmarefcovid_t_referto.documento_tipo_azione
     *
     * @mbg.generated
     */
    public String getDocumentoTipoAzione() {
        return documentoTipoAzione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dmarefcovid_t_referto.documento_tipo_azione
     *
     * @param documentoTipoAzione the value for dmarefcovid_t_referto.documento_tipo_azione
     *
     * @mbg.generated
     */
    public void setDocumentoTipoAzione(String documentoTipoAzione) {
        this.documentoTipoAzione = documentoTipoAzione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dmarefcovid_t_referto.episodio_tipo_azione
     *
     * @return the value of dmarefcovid_t_referto.episodio_tipo_azione
     *
     * @mbg.generated
     */
    public String getEpisodioTipoAzione() {
        return episodioTipoAzione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dmarefcovid_t_referto.episodio_tipo_azione
     *
     * @param episodioTipoAzione the value for dmarefcovid_t_referto.episodio_tipo_azione
     *
     * @mbg.generated
     */
    public void setEpisodioTipoAzione(String episodioTipoAzione) {
        this.episodioTipoAzione = episodioTipoAzione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dmarefcovid_t_referto.data_creazione
     *
     * @return the value of dmarefcovid_t_referto.data_creazione
     *
     * @mbg.generated
     */
    public Date getDataCreazione() {
        return dataCreazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dmarefcovid_t_referto.data_creazione
     *
     * @param dataCreazione the value for dmarefcovid_t_referto.data_creazione
     *
     * @mbg.generated
     */
    public void setDataCreazione(Date dataCreazione) {
        this.dataCreazione = dataCreazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dmarefcovid_t_referto.ts_msg_ricevuto
     *
     * @return the value of dmarefcovid_t_referto.ts_msg_ricevuto
     *
     * @mbg.generated
     */
    public Date getTsMsgRicevuto() {
        return tsMsgRicevuto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dmarefcovid_t_referto.ts_msg_ricevuto
     *
     * @param tsMsgRicevuto the value for dmarefcovid_t_referto.ts_msg_ricevuto
     *
     * @mbg.generated
     */
    public void setTsMsgRicevuto(Date tsMsgRicevuto) {
        this.tsMsgRicevuto = tsMsgRicevuto;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dmarefcovid_t_referto.ts_cda2_elaborato
     *
     * @return the value of dmarefcovid_t_referto.ts_cda2_elaborato
     *
     * @mbg.generated
     */
    public Date getTsCda2Elaborato() {
        return tsCda2Elaborato;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dmarefcovid_t_referto.ts_cda2_elaborato
     *
     * @param tsCda2Elaborato the value for dmarefcovid_t_referto.ts_cda2_elaborato
     *
     * @mbg.generated
     */
    public void setTsCda2Elaborato(Date tsCda2Elaborato) {
        this.tsCda2Elaborato = tsCda2Elaborato;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dmarefcovid_t_referto.asr_doc
     *
     * @return the value of dmarefcovid_t_referto.asr_doc
     *
     * @mbg.generated
     */
    public String getAsrDoc() {
        return asrDoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dmarefcovid_t_referto.asr_doc
     *
     * @param asrDoc the value for dmarefcovid_t_referto.asr_doc
     *
     * @mbg.generated
     */
    public void setAsrDoc(String asrDoc) {
        this.asrDoc = asrDoc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dmarefcovid_t_referto.cod_tipo_richiesta
     *
     * @return the value of dmarefcovid_t_referto.cod_tipo_richiesta
     *
     * @mbg.generated
     */
    public String getCodTipoRichiesta() {
        return codTipoRichiesta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dmarefcovid_t_referto.cod_tipo_richiesta
     *
     * @param codTipoRichiesta the value for dmarefcovid_t_referto.cod_tipo_richiesta
     *
     * @mbg.generated
     */
    public void setCodTipoRichiesta(String codTipoRichiesta) {
        this.codTipoRichiesta = codTipoRichiesta;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dmarefcovid_t_referto.programma
     *
     * @return the value of dmarefcovid_t_referto.programma
     *
     * @mbg.generated
     */
    public String getProgramma() {
        return programma;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dmarefcovid_t_referto.programma
     *
     * @param programma the value for dmarefcovid_t_referto.programma
     *
     * @mbg.generated
     */
    public void setProgramma(String programma) {
        this.programma = programma;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dmarefcovid_t_referto.asl_laboratorio
     *
     * @return the value of dmarefcovid_t_referto.asl_laboratorio
     *
     * @mbg.generated
     */
    public String getAslLaboratorio() {
        return aslLaboratorio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dmarefcovid_t_referto.asl_laboratorio
     *
     * @param aslLaboratorio the value for dmarefcovid_t_referto.asl_laboratorio
     *
     * @mbg.generated
     */
    public void setAslLaboratorio(String aslLaboratorio) {
        this.aslLaboratorio = aslLaboratorio;
    }

	public String getUtenteoperazione() {
		return utenteoperazione;
	}

	public void setUtenteoperazione(String utenteoperazione) {
		this.utenteoperazione = utenteoperazione;
	}
    
    
}