package it.csi.gestionepazienti.gestionepazientiweb.dto.referto;

import it.csi.gestionepazienti.gestionepazientiweb.dto.AbstractDto;
import java.util.Date;

public class RefertoDettaglio extends AbstractDto {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dmarefcovid_t_referto_det.intfrdet_id
     *
     * @mbg.generated
     */
    private Integer intfrdetId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dmarefcovid_t_referto_det.id_messaggio
     *
     * @mbg.generated
     */
    private Integer idMessaggio;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dmarefcovid_t_referto_det.code_displayname
     *
     * @mbg.generated
     */
    private String codeDisplayname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dmarefcovid_t_referto_det.code_code
     *
     * @mbg.generated
     */
    private String codeCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dmarefcovid_t_referto_det.effectivetime_value
     *
     * @mbg.generated
     */
    private Date effectivetimeValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dmarefcovid_t_referto_det.value_code
     *
     * @mbg.generated
     */
    private String valueCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dmarefcovid_t_referto_det.value_unit
     *
     * @mbg.generated
     */
    private String valueUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dmarefcovid_t_referto_det.value_interpretationcode
     *
     * @mbg.generated
     */
    private String valueInterpretationcode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dmarefcovid_t_referto_det.value_displayname
     *
     * @mbg.generated
     */
    private String valueDisplayname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dmarefcovid_t_referto_det.value_value
     *
     * @mbg.generated
     */
    private String valueValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dmarefcovid_t_referto_det.refrange_text
     *
     * @mbg.generated
     */
    private String refrangeText;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dmarefcovid_t_referto_det.refrange_low_value
     *
     * @mbg.generated
     */
    private String refrangeLowValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dmarefcovid_t_referto_det.refrange_low_unit
     *
     * @mbg.generated
     */
    private String refrangeLowUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dmarefcovid_t_referto_det.refrange_high_value
     *
     * @mbg.generated
     */
    private String refrangeHighValue;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dmarefcovid_t_referto_det.refrange_high_unit
     *
     * @mbg.generated
     */
    private String refrangeHighUnit;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column dmarefcovid_t_referto_det.data_creazione
     *
     * @mbg.generated
     */
    private Date dataCreazione;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dmarefcovid_t_referto_det.intfrdet_id
     *
     * @return the value of dmarefcovid_t_referto_det.intfrdet_id
     *
     * @mbg.generated
     */
    public Integer getIntfrdetId() {
        return intfrdetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dmarefcovid_t_referto_det.intfrdet_id
     *
     * @param intfrdetId the value for dmarefcovid_t_referto_det.intfrdet_id
     *
     * @mbg.generated
     */
    public void setIntfrdetId(Integer intfrdetId) {
        this.intfrdetId = intfrdetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dmarefcovid_t_referto_det.id_messaggio
     *
     * @return the value of dmarefcovid_t_referto_det.id_messaggio
     *
     * @mbg.generated
     */
    public Integer getIdMessaggio() {
        return idMessaggio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dmarefcovid_t_referto_det.id_messaggio
     *
     * @param idMessaggio the value for dmarefcovid_t_referto_det.id_messaggio
     *
     * @mbg.generated
     */
    public void setIdMessaggio(Integer idMessaggio) {
        this.idMessaggio = idMessaggio;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dmarefcovid_t_referto_det.code_displayname
     *
     * @return the value of dmarefcovid_t_referto_det.code_displayname
     *
     * @mbg.generated
     */
    public String getCodeDisplayname() {
        return codeDisplayname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dmarefcovid_t_referto_det.code_displayname
     *
     * @param codeDisplayname the value for dmarefcovid_t_referto_det.code_displayname
     *
     * @mbg.generated
     */
    public void setCodeDisplayname(String codeDisplayname) {
        this.codeDisplayname = codeDisplayname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dmarefcovid_t_referto_det.code_code
     *
     * @return the value of dmarefcovid_t_referto_det.code_code
     *
     * @mbg.generated
     */
    public String getCodeCode() {
        return codeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dmarefcovid_t_referto_det.code_code
     *
     * @param codeCode the value for dmarefcovid_t_referto_det.code_code
     *
     * @mbg.generated
     */
    public void setCodeCode(String codeCode) {
        this.codeCode = codeCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dmarefcovid_t_referto_det.effectivetime_value
     *
     * @return the value of dmarefcovid_t_referto_det.effectivetime_value
     *
     * @mbg.generated
     */
    public Date getEffectivetimeValue() {
        return effectivetimeValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dmarefcovid_t_referto_det.effectivetime_value
     *
     * @param effectivetimeValue the value for dmarefcovid_t_referto_det.effectivetime_value
     *
     * @mbg.generated
     */
    public void setEffectivetimeValue(Date effectivetimeValue) {
        this.effectivetimeValue = effectivetimeValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dmarefcovid_t_referto_det.value_code
     *
     * @return the value of dmarefcovid_t_referto_det.value_code
     *
     * @mbg.generated
     */
    public String getValueCode() {
        return valueCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dmarefcovid_t_referto_det.value_code
     *
     * @param valueCode the value for dmarefcovid_t_referto_det.value_code
     *
     * @mbg.generated
     */
    public void setValueCode(String valueCode) {
        this.valueCode = valueCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dmarefcovid_t_referto_det.value_unit
     *
     * @return the value of dmarefcovid_t_referto_det.value_unit
     *
     * @mbg.generated
     */
    public String getValueUnit() {
        return valueUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dmarefcovid_t_referto_det.value_unit
     *
     * @param valueUnit the value for dmarefcovid_t_referto_det.value_unit
     *
     * @mbg.generated
     */
    public void setValueUnit(String valueUnit) {
        this.valueUnit = valueUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dmarefcovid_t_referto_det.value_interpretationcode
     *
     * @return the value of dmarefcovid_t_referto_det.value_interpretationcode
     *
     * @mbg.generated
     */
    public String getValueInterpretationcode() {
        return valueInterpretationcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dmarefcovid_t_referto_det.value_interpretationcode
     *
     * @param valueInterpretationcode the value for dmarefcovid_t_referto_det.value_interpretationcode
     *
     * @mbg.generated
     */
    public void setValueInterpretationcode(String valueInterpretationcode) {
        this.valueInterpretationcode = valueInterpretationcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dmarefcovid_t_referto_det.value_displayname
     *
     * @return the value of dmarefcovid_t_referto_det.value_displayname
     *
     * @mbg.generated
     */
    public String getValueDisplayname() {
        return valueDisplayname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dmarefcovid_t_referto_det.value_displayname
     *
     * @param valueDisplayname the value for dmarefcovid_t_referto_det.value_displayname
     *
     * @mbg.generated
     */
    public void setValueDisplayname(String valueDisplayname) {
        this.valueDisplayname = valueDisplayname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dmarefcovid_t_referto_det.value_value
     *
     * @return the value of dmarefcovid_t_referto_det.value_value
     *
     * @mbg.generated
     */
    public String getValueValue() {
        return valueValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dmarefcovid_t_referto_det.value_value
     *
     * @param valueValue the value for dmarefcovid_t_referto_det.value_value
     *
     * @mbg.generated
     */
    public void setValueValue(String valueValue) {
        this.valueValue = valueValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dmarefcovid_t_referto_det.refrange_text
     *
     * @return the value of dmarefcovid_t_referto_det.refrange_text
     *
     * @mbg.generated
     */
    public String getRefrangeText() {
        return refrangeText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dmarefcovid_t_referto_det.refrange_text
     *
     * @param refrangeText the value for dmarefcovid_t_referto_det.refrange_text
     *
     * @mbg.generated
     */
    public void setRefrangeText(String refrangeText) {
        this.refrangeText = refrangeText;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dmarefcovid_t_referto_det.refrange_low_value
     *
     * @return the value of dmarefcovid_t_referto_det.refrange_low_value
     *
     * @mbg.generated
     */
    public String getRefrangeLowValue() {
        return refrangeLowValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dmarefcovid_t_referto_det.refrange_low_value
     *
     * @param refrangeLowValue the value for dmarefcovid_t_referto_det.refrange_low_value
     *
     * @mbg.generated
     */
    public void setRefrangeLowValue(String refrangeLowValue) {
        this.refrangeLowValue = refrangeLowValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dmarefcovid_t_referto_det.refrange_low_unit
     *
     * @return the value of dmarefcovid_t_referto_det.refrange_low_unit
     *
     * @mbg.generated
     */
    public String getRefrangeLowUnit() {
        return refrangeLowUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dmarefcovid_t_referto_det.refrange_low_unit
     *
     * @param refrangeLowUnit the value for dmarefcovid_t_referto_det.refrange_low_unit
     *
     * @mbg.generated
     */
    public void setRefrangeLowUnit(String refrangeLowUnit) {
        this.refrangeLowUnit = refrangeLowUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dmarefcovid_t_referto_det.refrange_high_value
     *
     * @return the value of dmarefcovid_t_referto_det.refrange_high_value
     *
     * @mbg.generated
     */
    public String getRefrangeHighValue() {
        return refrangeHighValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dmarefcovid_t_referto_det.refrange_high_value
     *
     * @param refrangeHighValue the value for dmarefcovid_t_referto_det.refrange_high_value
     *
     * @mbg.generated
     */
    public void setRefrangeHighValue(String refrangeHighValue) {
        this.refrangeHighValue = refrangeHighValue;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dmarefcovid_t_referto_det.refrange_high_unit
     *
     * @return the value of dmarefcovid_t_referto_det.refrange_high_unit
     *
     * @mbg.generated
     */
    public String getRefrangeHighUnit() {
        return refrangeHighUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dmarefcovid_t_referto_det.refrange_high_unit
     *
     * @param refrangeHighUnit the value for dmarefcovid_t_referto_det.refrange_high_unit
     *
     * @mbg.generated
     */
    public void setRefrangeHighUnit(String refrangeHighUnit) {
        this.refrangeHighUnit = refrangeHighUnit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column dmarefcovid_t_referto_det.data_creazione
     *
     * @return the value of dmarefcovid_t_referto_det.data_creazione
     *
     * @mbg.generated
     */
    public Date getDataCreazione() {
        return dataCreazione;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column dmarefcovid_t_referto_det.data_creazione
     *
     * @param dataCreazione the value for dmarefcovid_t_referto_det.data_creazione
     *
     * @mbg.generated
     */
    public void setDataCreazione(Date dataCreazione) {
        this.dataCreazione = dataCreazione;
    }
}