let LOCAL_DEV = ''
if (location.hostname === 'localhost' || location.hostname === '127.0.0.1') {
  LOCAL_DEV = 'http://localhost:8080/visurapazientiweb/'
}

const VERSION = '1.2'

const VISURAPAZIENTI_BASE_URL = LOCAL_DEV + 'api'

const ID_ISOLAMENTO_DOMICILIARE = 1
const ID_RICOVERATO = 2
const ID_TRASFERITO_INTERNO = 3
const ID_TRASFERITO_ESTERNO = 4
const ID_DECEDUTO = 5
const ID_GUARITO = 6
const ID_ATTESA_TEST = 8
const ID_POST_RICOVERO = 9
const ID_ASSEGNAZIONE_DOMICILIO = 10
const ID_ISOLAMENTO_FIDUCIARIO = 15
const ID_DISPOSTA_QUARANTENA_DOMIC = 16
const ID_DISPOSTA_QUARANTENA_EXTRA_DOMIC = 17

const ESITO_TAMPONE = {
  1: 'In corso',
  2: 'Positivo',
  4: 'Negativo',
  6: 'Sospeso',
  7: 'Non idoneo',
  8: 'Non pervenuto'
}

export default {
  VISURAPAZIENTI_BASE_URL: VISURAPAZIENTI_BASE_URL,
  ID_ISOLAMENTO_DOMICILIARE: ID_ISOLAMENTO_DOMICILIARE,
  ID_RICOVERATO: ID_RICOVERATO,
  ID_TRASFERITO_INTERNO: ID_TRASFERITO_INTERNO,
  ID_TRASFERITO_ESTERNO: ID_TRASFERITO_ESTERNO,
  ID_DECEDUTO: ID_DECEDUTO,
  ID_GUARITO: ID_GUARITO,
  ID_ATTESA_TEST: ID_ATTESA_TEST,
  ID_POST_RICOVERO: ID_POST_RICOVERO,
  ID_ASSEGNAZIONE_DOMICILIO: ID_ASSEGNAZIONE_DOMICILIO,
  ID_ISOLAMENTO_FIDUCIARIO: ID_ISOLAMENTO_FIDUCIARIO,
  ID_DISPOSTA_QUARANTENA_DOMIC: ID_DISPOSTA_QUARANTENA_DOMIC,
  ID_DISPOSTA_QUARANTENA_EXTRA_DOMIC: ID_DISPOSTA_QUARANTENA_EXTRA_DOMIC,
  ESITO_TAMPONE: ESITO_TAMPONE,
  VERSION: VERSION
}
