package it.csi.gestionepazienti.gestionepazientiweb.dto;

import java.util.Date;

public class RMedicoMedico extends AbstractDto {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column r_medico_medico.id_medico_medico
	 * @mbg.generated
	 */
	private Integer idMedicoMedico;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column r_medico_medico.id_medico_delegante
	 * @mbg.generated
	 */
	private Long idMedicoDelegante;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column r_medico_medico.id_medico_delegato
	 * @mbg.generated
	 */
	private Long idMedicoDelegato;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column r_medico_medico.validita_inizio
	 * @mbg.generated
	 */
	private Date validitaInizio;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column r_medico_medico.validita_fine
	 * @mbg.generated
	 */
	private Date validitaFine;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column r_medico_medico.utente_operazione
	 * @mbg.generated
	 */
	private String utenteOperazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column r_medico_medico.data_creazione
	 * @mbg.generated
	 */
	private Date dataCreazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column r_medico_medico.data_modifica
	 * @mbg.generated
	 */
	private Date dataModifica;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column r_medico_medico.data_cancellazione
	 * @mbg.generated
	 */
	private Date dataCancellazione;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column r_medico_medico.id_medico_medico
	 * @return  the value of r_medico_medico.id_medico_medico
	 * @mbg.generated
	 */
	public Integer getIdMedicoMedico() {
		return idMedicoMedico;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column r_medico_medico.id_medico_medico
	 * @param idMedicoMedico  the value for r_medico_medico.id_medico_medico
	 * @mbg.generated
	 */
	public void setIdMedicoMedico(Integer idMedicoMedico) {
		this.idMedicoMedico = idMedicoMedico;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column r_medico_medico.id_medico_delegante
	 * @return  the value of r_medico_medico.id_medico_delegante
	 * @mbg.generated
	 */
	public Long getIdMedicoDelegante() {
		return idMedicoDelegante;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column r_medico_medico.id_medico_delegante
	 * @param idMedicoDelegante  the value for r_medico_medico.id_medico_delegante
	 * @mbg.generated
	 */
	public void setIdMedicoDelegante(Long idMedicoDelegante) {
		this.idMedicoDelegante = idMedicoDelegante;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column r_medico_medico.id_medico_delegato
	 * @return  the value of r_medico_medico.id_medico_delegato
	 * @mbg.generated
	 */
	public Long getIdMedicoDelegato() {
		return idMedicoDelegato;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column r_medico_medico.id_medico_delegato
	 * @param idMedicoDelegato  the value for r_medico_medico.id_medico_delegato
	 * @mbg.generated
	 */
	public void setIdMedicoDelegato(Long idMedicoDelegato) {
		this.idMedicoDelegato = idMedicoDelegato;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column r_medico_medico.validita_inizio
	 * @return  the value of r_medico_medico.validita_inizio
	 * @mbg.generated
	 */
	public Date getValiditaInizio() {
		return validitaInizio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column r_medico_medico.validita_inizio
	 * @param validitaInizio  the value for r_medico_medico.validita_inizio
	 * @mbg.generated
	 */
	public void setValiditaInizio(Date validitaInizio) {
		this.validitaInizio = validitaInizio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column r_medico_medico.validita_fine
	 * @return  the value of r_medico_medico.validita_fine
	 * @mbg.generated
	 */
	public Date getValiditaFine() {
		return validitaFine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column r_medico_medico.validita_fine
	 * @param validitaFine  the value for r_medico_medico.validita_fine
	 * @mbg.generated
	 */
	public void setValiditaFine(Date validitaFine) {
		this.validitaFine = validitaFine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column r_medico_medico.utente_operazione
	 * @return  the value of r_medico_medico.utente_operazione
	 * @mbg.generated
	 */
	public String getUtenteOperazione() {
		return utenteOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column r_medico_medico.utente_operazione
	 * @param utenteOperazione  the value for r_medico_medico.utente_operazione
	 * @mbg.generated
	 */
	public void setUtenteOperazione(String utenteOperazione) {
		this.utenteOperazione = utenteOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column r_medico_medico.data_creazione
	 * @return  the value of r_medico_medico.data_creazione
	 * @mbg.generated
	 */
	public Date getDataCreazione() {
		return dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column r_medico_medico.data_creazione
	 * @param dataCreazione  the value for r_medico_medico.data_creazione
	 * @mbg.generated
	 */
	public void setDataCreazione(Date dataCreazione) {
		this.dataCreazione = dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column r_medico_medico.data_modifica
	 * @return  the value of r_medico_medico.data_modifica
	 * @mbg.generated
	 */
	public Date getDataModifica() {
		return dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column r_medico_medico.data_modifica
	 * @param dataModifica  the value for r_medico_medico.data_modifica
	 * @mbg.generated
	 */
	public void setDataModifica(Date dataModifica) {
		this.dataModifica = dataModifica;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column r_medico_medico.data_cancellazione
	 * @return  the value of r_medico_medico.data_cancellazione
	 * @mbg.generated
	 */
	public Date getDataCancellazione() {
		return dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column r_medico_medico.data_cancellazione
	 * @param dataCancellazione  the value for r_medico_medico.data_cancellazione
	 * @mbg.generated
	 */
	public void setDataCancellazione(Date dataCancellazione) {
		this.dataCancellazione = dataCancellazione;
	}
}