package it.csi.gestionepazienti.gestionepazientiweb.dto;

import java.math.BigDecimal;
import java.util.Date;

public class RSoggettoIstituto extends AbstractDto {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column r_soggetto_istituto.sog_ist_id
	 * @mbg.generated
	 */
	private Integer sogIstId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column r_soggetto_istituto.id_soggetto
	 * @mbg.generated
	 */
	private Integer idSoggetto;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column r_soggetto_istituto.id_istituto
	 * @mbg.generated
	 */
	private Integer idIstituto;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column r_soggetto_istituto.validita_inizio
	 * @mbg.generated
	 */
	private Date validitaInizio;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column r_soggetto_istituto.validita_fine
	 * @mbg.generated
	 */
	private Date validitaFine;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column r_soggetto_istituto.utente_operazione
	 * @mbg.generated
	 */
	private String utenteOperazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column r_soggetto_istituto.data_creazione
	 * @mbg.generated
	 */
	private Date dataCreazione;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column r_soggetto_istituto.data_modifca
	 * @mbg.generated
	 */
	private Date dataModifca;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column r_soggetto_istituto.data_cancellazione
	 * @mbg.generated
	 */
	private Date dataCancellazione;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column r_soggetto_istituto.sog_ist_id
	 * @return  the value of r_soggetto_istituto.sog_ist_id
	 * @mbg.generated
	 */
	public Integer getSogIstId() {
		return sogIstId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column r_soggetto_istituto.sog_ist_id
	 * @param sogIstId  the value for r_soggetto_istituto.sog_ist_id
	 * @mbg.generated
	 */
	public void setSogIstId(Integer sogIstId) {
		this.sogIstId = sogIstId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column r_soggetto_istituto.id_soggetto
	 * @return  the value of r_soggetto_istituto.id_soggetto
	 * @mbg.generated
	 */
	public Integer getIdSoggetto() {
		return idSoggetto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column r_soggetto_istituto.id_soggetto
	 * @param idSoggetto  the value for r_soggetto_istituto.id_soggetto
	 * @mbg.generated
	 */
	public void setIdSoggetto(Integer idSoggetto) {
		this.idSoggetto = idSoggetto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column r_soggetto_istituto.id_istituto
	 * @return  the value of r_soggetto_istituto.id_istituto
	 * @mbg.generated
	 */
	public Integer getIdIstituto() {
		return idIstituto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column r_soggetto_istituto.id_istituto
	 * @param idIstituto  the value for r_soggetto_istituto.id_istituto
	 * @mbg.generated
	 */
	public void setIdIstituto(Integer idIstituto) {
		this.idIstituto = idIstituto;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column r_soggetto_istituto.validita_inizio
	 * @return  the value of r_soggetto_istituto.validita_inizio
	 * @mbg.generated
	 */
	public Date getValiditaInizio() {
		return validitaInizio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column r_soggetto_istituto.validita_inizio
	 * @param validitaInizio  the value for r_soggetto_istituto.validita_inizio
	 * @mbg.generated
	 */
	public void setValiditaInizio(Date validitaInizio) {
		this.validitaInizio = validitaInizio;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column r_soggetto_istituto.validita_fine
	 * @return  the value of r_soggetto_istituto.validita_fine
	 * @mbg.generated
	 */
	public Date getValiditaFine() {
		return validitaFine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column r_soggetto_istituto.validita_fine
	 * @param validitaFine  the value for r_soggetto_istituto.validita_fine
	 * @mbg.generated
	 */
	public void setValiditaFine(Date validitaFine) {
		this.validitaFine = validitaFine;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column r_soggetto_istituto.utente_operazione
	 * @return  the value of r_soggetto_istituto.utente_operazione
	 * @mbg.generated
	 */
	public String getUtenteOperazione() {
		return utenteOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column r_soggetto_istituto.utente_operazione
	 * @param utenteOperazione  the value for r_soggetto_istituto.utente_operazione
	 * @mbg.generated
	 */
	public void setUtenteOperazione(String utenteOperazione) {
		this.utenteOperazione = utenteOperazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column r_soggetto_istituto.data_creazione
	 * @return  the value of r_soggetto_istituto.data_creazione
	 * @mbg.generated
	 */
	public Date getDataCreazione() {
		return dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column r_soggetto_istituto.data_creazione
	 * @param dataCreazione  the value for r_soggetto_istituto.data_creazione
	 * @mbg.generated
	 */
	public void setDataCreazione(Date dataCreazione) {
		this.dataCreazione = dataCreazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column r_soggetto_istituto.data_modifca
	 * @return  the value of r_soggetto_istituto.data_modifca
	 * @mbg.generated
	 */
	public Date getDataModifca() {
		return dataModifca;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column r_soggetto_istituto.data_modifca
	 * @param dataModifca  the value for r_soggetto_istituto.data_modifca
	 * @mbg.generated
	 */
	public void setDataModifca(Date dataModifca) {
		this.dataModifca = dataModifca;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column r_soggetto_istituto.data_cancellazione
	 * @return  the value of r_soggetto_istituto.data_cancellazione
	 * @mbg.generated
	 */
	public Date getDataCancellazione() {
		return dataCancellazione;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column r_soggetto_istituto.data_cancellazione
	 * @param dataCancellazione  the value for r_soggetto_istituto.data_cancellazione
	 * @mbg.generated
	 */
	public void setDataCancellazione(Date dataCancellazione) {
		this.dataCancellazione = dataCancellazione;
	}
}